= 16 September 2024
:page-aliases: 2024-09-16.adoc

link:https://youtu.be/EgyzjAlF1d0[Meeting recording]

== Attendees

* Andy Rosen, Sequence Key
* Christian Paquin, Microsoft
* Cullen Miller, Spawning AI
* Daniel Zellmer, Noosphere Technologies
* Drummond Reed, Gen Digital
* Eli Mallon, Aquareum
* Eric Scouten, Adobe
* Gavin Peacock, Adobe
* Jesse Carter, CIRA
* Karen Kilroy, FileBaby
* Konrad Bleyer-Simon, Global Media Registry
* Liviu Gheorghe, Adobe
* Loren Hart, Noosphere Technologies
* Michael Becker, Identity Praxis
* Nigel Earnshaw, BBC
* Peleus Uhley, Adobe
* Pia Blumenthal, Adobe
* Richard W. Kroon, EIDR
* Scott Perry, Digital Governance Institute
* Slava Asipenko, Proof
* Tim Cappalli, Okta

== Notes

include::partial$upcoming-meeting-changes.adoc[]

=== New members introduction

No new members this week.

=== Review previous action items

🎥 _1'20":_ Review action items from previous meeting:

* *ACTION:* Eric to revise PR 162 to include some consideration of localization and possibly a definition of user-visible string. *NOT DONE, CARRY OVER* but new information that Eric can work with.
* *ACTION:* Liviu and Eric to do further coding / research work to describe what the `proof` data structure should look like in this case. *NOT DONE* → *WON'T DO* based on subsequent decision of group.
* *ACTION:* Pam to discuss CBOR signing proposal with Microsoft engineering team and report back next week. *UPDATE:* Christian conveyed no objection on behalf of Microsoft.
* *ACTION:* Eric to explore whether we can reuse the COSE protected header mechanism for RFC 3161 timestamping in the VC approach. *NO UPDATE, CARRY OVER*
* *ACTION:* Eli to submit a PR adding support for K-256 signatures in CAWG. Group to discuss once available. *NOT DONE*
* *ACTION (✅):* Eli to submit a GitHub issue for the group to consider EIP-712 credentials as an autonomous signing mechanism. (See link:https://github.com/creator-assertions/identity-assertion/issues/176[Issue #176: Consider implications of autonomous signing mechanisms], to be discussed later.)
* *ACTION:* Jacques to submit a GitHub issue for the group to consider using domain-name based DIDs as an autonomous signing mechanism. *NO UPDATE, CARRY OVER*

=== Review PR #167: Define VC proofing mechanism

🎥 _5'33":_ Discussed link:https://github.com/creator-assertions/identity-assertion/pull/167[PR #167: Define VC proofing mechanism].

* We contemplated and decided not to include `did:key` as an acceptable DID method for identity claims aggregators.

*ACTION (✅):* Eric to remove reference to `did:jwk` and merge.

=== Review PR #180: Rewrite verifiable presentation example

🎥 _10'21":_ Discussed link:https://github.com/creator-assertions/identity-assertion/pull/180[PR #180: Rewrite verifiable presentation example].

Key points: 

* Eric updated the workflow for verifiable presentations, detailing the process from presentation requests to the generation of asset-specific verifiable credentials by the identity claims aggregator.
* Eric and Drummond emphasized the critical role of the identity claims aggregator in the ecosystem, responsible for verifying and replaying identity claims on asset-specific credentials.
* Concerns were raised about the potential security risks associated with rogue identity claims aggregators, stressing the need for a trust list to distinguish trustworthy entities.

*ACTION (✅):* Eric to merge.

=== Review issue #177: Define a way to prove control over a web site / domain and link it to identity claims aggregation

🎥 _43'21":_ Discussed link:https://github.com/creator-assertions/identity-assertion/issues/177[issue #177: Define a way to prove control over a web site / domain and link it to identity claims aggregation]

Brainstorming discussion, looking for protocols to consider or other proposals. Some highlights:

* Review Mastodon and AT protocol (Bluesky) for proving control over a domain for social media purposes (link:https://atproto.com/guides/identity[Documentation for AT protocol technique])
* Token in meta tag or DNS record
* CA / Browser Forum guidelines for issuance and management of Extended Validation Certificates §3.2.2 covers assurance that a web site is controlled by the specific legal entity described in the cert
* I believe the OpenID community long ago did a spec for "site claiming" so that a blog owner could prove control of a blog to an OpenID provider.
* `did:web` may provide a mechanism for this, too

Separately, we may also want to consider documenting content _created_ specifically as part of a site-generation process.

*ACTION:* Eric to create a PR incorporating above feedback.

=== Review issue #179: Describe how ICA should request a Verifiable Presentation and how to describe that in VC

🎥 _43'21":_ Discussed link:https://github.com/creator-assertions/identity-assertion/issues/179[issue #179: Describe how ICA should request a Verifiable Presentation and how to describe that in VC].

Key points:

* Significant questions about what trust ecosystems an identity claims aggregator will participate in when _collecting_ credentials. (Probable answer: That's implementation dependent and not to be specified here.)
* Separately, there is the question of what trust ecosystem the asset-specific credentials _issued_ bhy the identity claims aggregator should participate in. (Diverse opinions along the spectrum from CAWG should organize a identity claims aggregator-specific trust list to let the market of verifiers decide.)
* Look into link:https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html[OpenID Connect for Identity Assurance] spec as a possible vocabulary for expressing what has been learned about named actor through presentation requests.
* A reminder that not all information contained in the VP should be replayed by the identity claims aggregator into the subsequent asset-specific credential.

*ACTION:* Eric to create a PR incorporating above feedback.

=== Review issue #181: Remove affiliation from identity claims aggregation?

🎥 _1h09'06":_ Discussed link:https://github.com/creator-assertions/identity-assertion/issues/181[issue #181: Remove affiliation from identity claims aggregation?]

Is “affiliation” meaningfully different from what will be expressed via verifiable presentation?

No strong request for such.

*ACTION:* Eric to create a PR removing affiliation from spec.

=== Review issue #176: Consider implications of autonomous signing mechanisms

🎥 _1h12'48":_ Discussed link:https://github.com/creator-assertions/identity-assertion/issues/176[issue #176: Consider implications of autonomous signing mechanisms].

Eli showcased a demo on autonomous signing mechanisms using crypto wallets, advocating for the inclusion of such technologies in the CAWG spec to accommodate evolving user signing flows and identity assertion methods. (link:https://youtu.be/EgyzjAlF1d0?si=xo4SMkDiN274TxWI&t=4432[Watch the demo starting at 1h13'52".])

The discussion suggested that as user signing flows evolve, incorporating autonomous signing mechanisms could become increasingly relevant for identity assertion in the CAWG ecosystem.

CAWG open to considering autonomous signing mechanisms after focusing on identity claims aggregation.
