= 07 October 2024
:page-aliases: 2024-10-07.adoc

link:https://youtu.be/xTUN-j7eUbY[Meeting recording]

== Attendees

* Andreas Reich, TrustNXT
* Andy Rosen, Sequence Key
* Claudiu Cismaru, Adobe
* David Bigsby, Government of British Columbia
* Eli Mallon, Aquareum
* Eric Scouten, Adobe
* Gavin Peacock, Adobe
* Hans Granqvist, Noosphere
* Karen Kilroy, FileBaby
* Konrad Bleyer-Simon, Global Media Registry
* Loren Hart, Noosphere Technologies
* Nigel Earnshaw, BBC
* Pamela Dingle, Microsoft
* Peleus Uhley, Adobe
* Richard W. Kroon, EIDR
* Scott Perry, Digital Governance Institute
* Steven Milstein, Trust Over IP Foundation
* Tim Cappalli, Okta
* Utkarsh Sharma, Vlinder

== Notes

=== New members introduction

* 🎥 _1'11":_ Claudiu Cismaru, Adobe

=== Trust Over IP discussion

🎥 _2'25":_ Steven Milstein from link:https://trustoverip.org[Trust Over IP Foundation]’s link:++https://lf-toip.atlassian.net/wiki/spaces/HOME/pages/22982892/AI+Metaverse+Technology+Task+Force?pageId=22982892++[AI and Metaverse Task Force] joined us and introduced ToIP’s link:https://trustoverip.github.io/tswg-tsp-specification/[Trust Spanning Protocol] and discussed the idea of a potential integration with C2PA and/or CAWG.

Eric and Steven highlighted the differences between C2PA and Trust Spanning Protocol. C2PA and CAWG focus on content and metadata embedding within digital media file formats, while Trust Spanning Protocol is more about secure point-to-point communication and identity verification.

Steven discussed the potential for C2PA to use the Trust Spanning Protocol in its workflow, suggesting that it could help in the adoption of C2PA by providing a secure messaging layer.

Eric acknowledged the challenges of widespread adoption of decentralized identity, noting that it is not yet sufficiently widespread for CAWG to adopt it fully. He emphasized the need to follow trends and advocate for adoption when the time is right.

Steven and Eric discussed the importance of governance in decentralized identity, with Steven noting that governance is about relationships and trust rather than just technology. Eric added that CAWG aims to support evolving identity technologies within its framework.

=== Review previous action items

🎥 _18'25":_ Briefly reviewed the following action items from last week. Most of these translated into PRs that we discussed later.

* *ACTION:* Eric to propose additional language explaining the identity claims aggregator model. Feedback received before and during the meeting suggests it is not sufficiently clear yet. *NOT DONE*
* *ACTION:* Eric to propose a PR that suggests other identity types (non `cawg.`) should follow reverse domain syntax. *DONE*
* *ACTION:* Eric to review potential domain control verification methods with UX and product management to determine suitability. *IN PROGRESS*
* *ACTION:* Eric to propose a PR deleting the `proof` section. *DONE*
* *ACTION:* Eric to propose a PR with RFC 3161 in COSE signature for identity claims aggregation model.

=== PR #190: Consolidate wording about `cawg.` labels

🎥 _19'37":_ Discussed link:https://github.com/creator-assertions/identity-assertion/pull/190[PR #190: Consolidate wording about `cawg.` labels].

*ACTION (✅):* Eric to merge PR.

=== PR #191: Remove `proof` entry from `verifiedIdentities\[n\]` structure

🎥 _22'54":_ Discussed link:https://github.com/creator-assertions/identity-assertion/pull/191[PR #191: Remove `proof` entry from `verifiedIdentities\[n\]` structure].

*ACTION (✅):* Eric to merge PR.

=== PR #192: Add option to use RFC 3161 timestamp in ICA COSE signature

🎥 _25'52":_ Discussed link:https://github.com/creator-assertions/identity-assertion/pull/192[PR #192: Add option to use RFC 3161 timestamp in ICA COSE signature].

*ACTION (✅):* Eric to merge PR.

=== PR #187: Add support for verified presentations

🎥 _31'14":_ Discussed link:https://github.com/creator-assertions/identity-assertion/pull/187[PR #187: Add support for verified presentations].

**Inclusion:** Eric discussed the inclusion of verified presentations in the identity assertion, explaining that this would allow for the inclusion of credentials such as driver’s licenses and professional accreditations.

**Sensitive Information:** The group discussed concerns about sensitive information being included in the verified presentations. Tim suggested providing guidance on what should be redacted to prevent the inadvertent sharing of private information.

**Proof Request:** David raised the point that the information included in the verified presentation is driven by the proof request from the claims aggregator. He suggested that the spec should call out what information is requested and how it should be handled.

**Trust and Governance:** Pamela emphasized the importance of distinguishing between protocol implementation and trust framework governance. She suggested that considerations should be included in the spec, but the governance rules should be defined elsewhere.

*ACTION:* Eric to call subgroup meeting to refine the proposal.

=== Discussion about trust infrastructure

🎥 _46'38":_ Nigel raised concerns about the trust infrastructure for identity claims aggregators (ICAs), questioning how to ensure that ICAs are credible and trustworthy.

Eric acknowledged the need for a governance process to ensure the credibility of ICAs. He mentioned that there are ongoing discussions about establishing a trust infrastructure for ICAs.

=== PR #188: Add support for domain control validation (DCV) aka verified web site

🎥 _50'42":_ Discussed link:https://github.com/creator-assertions/identity-assertion/pull/188[PR #188: Add support for domain control validation (DCV) aka verified web site].

Eric discussed the methods for verifying control over a web domain, including DNS text records and meta tags, and the potential challenges of using these techniques.

*ACTION* (underway): Eric working with Adobe product management to understand consumer viability of these techniques.

*ACTION:* Eric to explore how to avoid collision between DNS tags from multiple vendors.

=== Issue #53: Explore questions of anonymized credentials and how they might be expressed in the standard

🎥 _57'43":_ Discussed link:https://github.com/creator-assertions/identity-assertion/issues/53[issue #53: Explore questions of anonymized credentials and how they might be expressed in the standard].

Is this relevant for ICA model or should it be considered as part of a future 1.x enhancement?

*ACTION:* Eric to call meeting with BC representatives including Stephen Curran, Lindsay Walker (who originally raised the issue), and potentially Will Kreth to discuss further.

=== Issue #32: Levels of assurance for subject credentials?

🎥 _1h01'01":_ Discussed link:https://github.com/creator-assertions/identity-assertion/issues/32[issue #32: Levels of assurance for subject credentials?]

Scott shared a link to link:https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/eIDAS+Levels+of+Assurance[eIDAS Levels of Assurance].

Important concepts:

* ICA will need to state the level of assurance it ascribes to the identity claim that it has received and is relaying.
* eIDAS does a good job of describing the level of confidence in the claimed identity.
