= 22 April 2024
:page-aliases: 2024-04-22.adoc

link:https://youtu.be/wwdeiEJ_J4E[Meeting recording]

== Attendees

* Andy Parsons, Adobe
* Andy Rosen
* Carly Huitema, U of Guelph
* Charlie Halford, BBC
* Chris ___, Verus
* Christian Paquin, Microsoft
* Clement Hecquet, Digimarc
* Drummond Reed, Gen Digital
* Eric Scouten, Adobe
* Gavin Peacock, Adobe
* Jesse Carter, CIRA
* Krishna Sood, Microsoft
* Loren Hart, Noosphere Technologies
* Michael Becker, Identity Praxis
* Nigel Earnshaw, BBC
* Patrick Boehler, independent consultant
* Peleus Uhley, Adobe
* Pia Blumenthal, Adobe
* Radu Ghiorghisor, Adobe
* Will Kreth, HAND (Human & Digital) Identity

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

=== 5 min: New members introduction

* 🎥 _2'22":_ Clement Hecquet, Digimarc
* 🎥 _2'58":_ Krishna Sood, Microsoft
* 🎥 _3'24":_ Loren Hart, Noosphere Technologies

=== Endorsement assertion

🎥 _2'22":_ Discussion about link:https://github.com/creator-assertions/endorsement-assertion/issues/1[issue #1: Can there be more than one endorsement assertion per claim?]. Conclusion: Yes, there are valid use cases for that.

🎥 _14'21":_ *ACTION* (existing link:https://github.com/creator-assertions/endorsement-assertion/issues/1[issue #1]): Eric to draft new wording to explicitly permit multiple endorsements per manifest.

🎥 _14'37":_ *ACTION* (new link:https://github.com/creator-assertions/endorsement-assertion/issues/4[issue #4]): Eric to draft new wording describing potential multi-CDN use case.

🎥 _16'09":_ *ACTION* (new link:https://github.com/creator-assertions/endorsement-assertion/issues/5[issue #5], not a 1.0 blocker): Pia and Nick to work on UX guidance for interpreting endorsement assertions.

=== 20 min: IIW readout and discussion

🎥 _17'31":_ Initial description of IIW and what it's about. General sense that this was one of the more intense IIWs.

🎥 _20'47":_ I described the three CAI/C2PA/CAWG-related sessions that I led or co-led:

* *Tuesday:* Content Authenticity 101, intended as a start-from-nothing introduction to the Content Authenticity space
* *Wednesday:* Content Authenticity 201, a deeper dive on the CAWG identity assertion and some of the interesting challenges we're facing in that space now
* *Thursday:* Content Authenticity UX (co-led with Pia Blumenthal) describing current C2PA UX guidance and how forthcoming CAWG UX guidance will build upon that

🎥 _22'27":_ I walked through the slide deck of the Wednesday session and described some of the feedback I received. Summary, excerpted from my notes:

* *Broadcast application* _(slide 26):_ Encode as much as possible into the asset VC. This also helps mitigate the “phone home” at time of verification potential harm.
* *Interoperability* _(slide 29):_ Sam suggested to focus on major example DID methods. There’s an upcoming registry of DID methods supported by US gov. Pay attention to that. Also, someone recommended using the link:https://dev.uniresolver.io/[DIF Universal Resolver] to address the DID interop issue. Universal Resolver understands about 60 methods, which is probably a good starting point for what to support.
* *Duplicate identity* _(slide 30):_ Perhaps the DID identifier is more important than the name.
* *Bulk signing* _(slide 31):_ As long as consent is there, authorization of each one is not important.
* *Social media* _(slide 32):_ No such standard exists today.

Scott Perry approached me after the session and encourged me to review the link:https://trustoverip.org/permalink/Issuer-Requirements-Guide-V0.01-2024-01-30.pdf[ToIP Issuer Requirements Guide for Governance Frameworks for Verifiable Credentials]. This document provides guidances for several of the thorny questions I raised in the session.

🎥 _46'42":_ Pia gave a readout on the UX presentation that she led at IIW, focusing on how upcoming work in CAWG will build upon the progressive disclosure framework already established at C2PA. Some specific issues raised:

* Provenance of identity information
* Describing the different tiers of identity verification (also known as "levels of assurance")

More reading online:

* *link:https://ericscouten.dev/2024/iiw38/[ericscouten.dev: IIW 38]* contains my notes for the overall conference, including the CAI/C2PA/CAWG-related sessions and their slide decks.
* *link:https://ericscouten.dev/2024/content-authenticity-101/[ericscouten.dev: Content Authenticity 101]* contains a condensed version of the talk from Tuesday along with the slide deck I used for that talk.
* *link:https://northernblock.io/blog/iiw38-summary/[northernblock.io: A Summary of Internet Identity Workshop #38]* contains notes from Mathieu Glaude of Northern Block

=== 30 min: Discussion on signer payload fixes PR

Walk through link:https://github.com/creator-assertions/identity-assertion/pull/96[PR #96: Signer payload fixes] and discuss potential updates to it.

🎥 _49'16":_ Briefly discussed and then tabled as Paul England (PR author) was not present today.

=== 25 min: Discuss remaining issues for 1.0 specification

🎥 _52'04":_ Walk through link:https://github.com/creator-assertions/identity-assertion/milestone/1[Open issues for 1.0 milestone] and explore how to resolve those issues.

* Several remaining issues pertain to trust model. *ACTION:* Eric to distill discussion in the open issues into a new PR for identity assertion.

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
