site:
  title: Creator Assertions Working Group
  url: https://creator-assertions.github.io
  start_page: ROOT::index.adoc

content:
  sources: 
  - url: https://github.com/creator-assertions/creator-assertions.github.io.git
    branches: main
    start_path: docs
    edit_url: ~ 

  - url: https://github.com/creator-assertions/identity-assertion.git
    branches: 
    - HEAD
    - '1.x-add-w3c-vc-v2'
    start_path: docs

  - url: https://github.com/creator-assertions/endorsement-assertion.git
    branches: main
    start_path: docs

  - url: https://github.com/creator-assertions/metadata-assertion.git
    branches: []
    tags: v1.0
    start_path: docs

  - url: https://github.com/creator-assertions/training-and-data-mining-assertion.git
    branches: []
    tags: v1.0
    start_path: docs

urls:
  html_extension_style: indexify

ui: 
  bundle:
    url: https://creator-assertions.github.io/antora-ui/ui-bundle.zip
    snapshot: true

antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_initialize_options:
        theme_variables:
          font_family: Roboto,sans-serif
