site:
  title: Specifications
  # url: https://specs.tbd.org
  start_page: specifications::index.adoc
content:
  sources: 
  - url: git@github.com:content-authorship/specs-site.git
    branches: main
    start_path: docs
  - url: https://github.com/content-authorship/identity.git
    branches: HEAD
    start_path: docs
  - url: https://github.com/content-authorship/training-and-data-mining.git
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: https://voluble-treacle-74ce0d.netlify.app/ui-bundle.zip
    snapshot: true
