site:
  title: Specifications
  # url: https://specs.tbd.org
  start_page: specifications::index.adoc
content:
  sources: 
  - url: git@github.com:content-authorship/specs-site.git
    branches: main
    start_path: docs
  - url: https://github.com/content-authorship/endorsement.git
    branches: main
    start_path: docs
  - url: https://github.com/content-authorship/identity.git
    branches:
      - main
    start_path: docs
  - url: https://github.com/content-authorship/metadata.git
    branches: main
    start_path: docs
  - url: https://github.com/content-authorship/training-and-data-mining.git
    branches: main
    start_path: docs
ui: 
  bundle:
    url: https://voluble-treacle-74ce0d.netlify.app/ui-bundle.zip
    snapshot: true
antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_initialize_options:
        theme_variables:
          font_family: Roboto,sans-serif
    - '@antora/pdf-extension'
