site:
  title: Specifications
  # url: https://specs.tbd.org
  start_page: specifications::index.adoc
content:
  sources: 
  - url: git@github.com:creator-assertions/specs-site.git
    branches: main
    start_path: docs
  - url: https://github.com/creator-assertions/endorsement-assertion.git
    branches: main
    start_path: docs
  - url: https://github.com/creator-assertions/identity-assertion.git
    branches:
      - main
    start_path: docs
  - url: https://github.com/creator-assertions/metadata-assertion.git
    branches: main
    start_path: docs
  - url: https://github.com/creator-assertions/training-and-data-mining-assertion.git
    branches: main
    start_path: docs
ui: 
  bundle:
    url: https://voluble-treacle-74ce0d.netlify.app/ui-bundle.zip
    snapshot: true
antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_initialize_options:
        theme_variables:
          font_family: Roboto,sans-serif
