= 29 April 2024

link:https://youtu.be/MtAXEaPWMgs[Meeting recording]

== Attendees

* Andy Parsons, Adobe
* Andy Rosen
* Carly Huitema, U of Guelph
* Charlie Halford, BBC
* Christian Paquin, Microsoft
* Clement Hecquet, Digimarc
* David Springgay, Microsoft
* Drummond Reed, Gen Digital
* Eric Scouten, Adobe
* Gavin Peacock, Adobe
* Jesse Carter, CIRA
* Lindsay Walker, Starling Labs
* Loren Hart, Noosphere Technologies
* Michael Becker, Identity Praxis
* Nigel Earnshaw, BBC
* Paul England, Microsoft
* Peleus Uhley, Adobe
* Pia Blumenthal, Adobe
* Radu Ghiorghisor, Adobe
* Will Kreth, HAND (Human & Digital) Identity

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

=== 5 min: New members introduction

No new members today.

=== Endorsement assertion

🎥 _0'50":_ Walk through link:https://github.com/creator-assertions/endorsement-assertion/pull/6[PR #6: Substantial rewrite, introducing the terms endorser and endorsee, and clarifying the workflow for each role].

*ACTION (✅):* Eric to revise PR based on feedback in meeting. Now awaiting re-review from Charlie and Leonard.

*ACTION (✅):* Eric to split out suggestion on interoperability with identity assertion into new issue to be considered later. New link:https://github.com/creator-assertions/endorsement-assertion/issues/8[issue #8] queued up for post-1.0 discussion.

=== 15 min: Define named actor’s role

🎥 _7'45":_ Walk through link:https://github.com/creator-assertions/identity-assertion/pull/98[PR #98: Introduce an optional `signer_payload.role` field].

*ACTION:* Eric to review feedback in PR and update for re-review next week.

=== 5 min: Discuss “multiple step processing” issue

🎥 _24'01":_ Walk through link:https://github.com/creator-assertions/identity-assertion/issue/63[issue #63: Possible interaction in “multiple step processing”]. Close or discuss any needed action items.

*ACTION:* Eric to refer this to C2PA TWG and close the CAWG issue.

=== 35 min: Discuss trust and threat model PR

🎥 _28'36":_ Walk through link:https://github.com/creator-assertions/identity-assertion/pull/99[PR #99: Define identity assertion trust model], which also includes formal descriptions of prior issue discussions on _threat_ models.

*ACTION:* Eric to update PR based on discussion. (See comments in the PR.)

*ACTION:* Radu to discuss "Trust scenarios in identity assertion" with Adobe IMS team to see if 9.2.3 can be deleted.

=== 5 min: Discuss overview section PR

🎥 _1h08'05":_ Walk through link:https://github.com/creator-assertions/identity-assertion/pull/102[PR #102: Clarify identity assertion “Overview” section].

*ACTION (✅):* Eric to merge PR after making suggestions from meeting.

=== 15 min: Discuss security model PR

🎥 _1h14'29":_ Walk through link:https://github.com/creator-assertions/identity-assertion/pull/96[PR #96: Signer payload fixes].

IMPORTANT: Some key participants in the substance of this discussion are not able to join today’s meeting, so this will be a discussion, but not a resolution of this issue.

*OUTCOME:* Good discussion about the motivation for this PR. Will continue discussion in subsequent meeting. No action items.

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
