= 16 September 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== 5 min: Review previous action items

Review action items from previous meeting:

* *ACTION:* Eric to revise PR 162 to include some consideration of localization and possibly a definition of user-visible string. *NOT DONE, CARRY OVER*
* *ACTION:* Liviu and Eric to do further coding / research work to describe what the `proof` data structure should look like in this case. *NOT DONE* (De-prioritize given shift to identity claim aggregation?)
* *ACTION:* Pam to discuss CBOR signing proposal with Microsoft engineering team and report back next week. *NO UPDATE, CARRY OVER*
* *ACTION:* Eric to explore whether we can reuse the COSE protected header mechanism for RFC 3161 timestamping in the VC approach. *NO UPDATE, CARRY OVER*
* *ACTION:* Eli to submit a PR adding support for K-256 signatures in CAWG. Group to discuss once available. *NOT DONE, CARRY OVER*
* *ACTION (✅):* Eli to submit a GitHub issue for the group to consider EIP-712 credentials as an autonomous signing mechanism. (See link:https://github.com/creator-assertions/identity-assertion/issues/176[Issue #176: Consider implications of autonomous signing mechanisms], to be discussed later.)
* *ACTION:* Jacques to submit a GitHub issue for the group to consider using domain-name based DIDs as an autonomous signing mechanism.

=== 20 min: Review open PRs against identity assertion

* link:https://github.com/creator-assertions/identity-assertion/pull/167[PR #167: Define VC proofing mechanism]
* link:https://github.com/creator-assertions/identity-assertion/pull/180[PR #180: Rewrite verifiable presentation example]

=== 30 min: Review open issues against identity assertion

* link:https://github.com/creator-assertions/identity-assertion/issues/177[Issue #177: Define a way to prove control over a web site / domain and link it to identity claims aggregation]
* link:https://github.com/creator-assertions/identity-assertion/issues/179[Issue #179: Describe how ICA should request a Verifiable Presentation and how to describe that in VC]
* link:https://github.com/creator-assertions/identity-assertion/issues/181[Issue #181: Remove affiliation from identity claims aggregation?]
* link:https://github.com/creator-assertions/identity-assertion/issues/176[Issue #176: Consider implications of autonomous signing mechanisms]

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.

Reminder: No meeting next week (23 September).
