= 08 April 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== 5 min: Update on endorsement assertion

If relevant members are present, discuss proposed update to endorsement assertion.

*MOTION:* Approve link:https://github.com/creator-assertions/endorsement-assertion/pull/2/files[PR #2] to merge.

=== 10 min: Review `tbs` to `signer_payload` PR

Follow-up to discussion from previous meeting about renaming `tbs` to `signer_payload`.

*MOTION:* Approve link:https://github.com/creator-assertions/identity-assertion/pull/89[PR #89] to merge.

=== 20 min: Review VC version take 3

Follow-up to discussions with Adobe stakeholders. Walk through proposed changes.

*MOTION:* Approve link:https://github.com/creator-assertions/identity-assertion/pull/90[PR #90] as working draft for 1.x (VC) version of identity assertion specification.

=== 10 min: Review PR to allow additional credential mechanisms in 1.x spec

*MOTION:* Approve link:https://github.com/creator-assertions/identity-assertion/pull/74[PR #74: Allow additional credential mechanisms to be added in future 1.x versions] to merge.

=== 15 min: Review bidirectional binding issue (issue #67)

Discuss link:https://github.com/creator-assertions/identity-assertion/issues/67[issue #67: Bidirectional binding of identity assertions and claims]. Can we close this issue soon?

=== 15 min: Discuss trust model (issue #22)

Discuss link:https://github.com/creator-assertions/identity-assertion/issues/22[issue #22: Define identity assertion trust model]. What are the basic requirements for the trust model?

=== (if time): Follow up on zero-knowledge proof discussion (issue #84)

Christian Paquin added new comments about ZKP and AnonCreds in link:++https://github.com/creator-assertions/identity-assertion/issues/84#issuecomment-2038243729++[issue #89: Discussion of Zero Knowledge Identity Management].

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
