= 06 May 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== 30 min: Review claim/claim-generator PR

See link:https://github.com/creator-assertions/identity-assertion/pull/103[PR #103].

Changes made since last week’s first draft:

* SHA-256 is no longer hard-coded. Updated to add an `alg` parameter and match the C2PA’s list of recognized hash algorithms.
* Proofreading suggestions from Christian and Paul.

Open issues:

* How to allow multiple identity assertions to use these protections?
** Zeroing out other identity assertions?
** Compute identity assertions in sequence?
** Allow only “last” identity assertion to use claim hash protection?

* Do we need the full cert chain or can we simplify to end-entity cert only?
* OK to close #96 without merging?

=== 15 min: Proposal: Declare implementer’s draft

See link:https://github.com/creator-assertions/identity-assertion/pull/104[PR #104] which will allow implementers to proceed using the core structure of the identity assertion while non-structural details are resolved.

NOTE: This is a heads-up discussion. I would like to move for merging this PR in the next meeting on 20 May. If the idea of locking the core structure of the identity assertion causes heartache, please speak up within these two weeks.

=== 15 min: Review trust model PR

See link:https://github.com/creator-assertions/identity-assertion/pull/99[PR #99].

=== 10 min: Endorsement assertion ready to approve?

Those who are interested in the endorsement, please re-review link:https://creator-assertions.github.io/endorsement/1.0-draft/[the latest draft], which includes changes approved last week.

I’d like to move for approval of 1.0 final specification in next meeting (20 May).

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.

IMPORTANT: Reminder that next week’s meeting (13 May) is cancelled due to an internal Adobe event.
