= 25 March 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== 5 min: Endorsement assertion PR

Review link:https://github.com/creator-assertions/endorsement-assertion/pull/2[one open PR] on the endorsement assertion.

NOTE: Assuming this PR is approved, I intend to put this forward for 1.0 final status in the *1 April 2024* meeting.

=== 45 min: Review open PRs for 1.0 specification

Review link:https://github.com/creator-assertions/identity-assertion/pulls?q=is%3Aopen+is%3Apr+milestone%3A1.0[6 open PRs] against 1.0 milestone.

Prioritize these two PRs that are fundamental and have the potential to block or reshape other work:

* link:https://github.com/creator-assertions/identity-assertion/pull/75[#75: Add top-level `tbs` map allowing more content to be signed by credential holder] – This will enable other planned work (notably Paul England's proposal about describing role).
* link:https://github.com/creator-assertions/identity-assertion/pull/82[#82: Use assertion label to describe credential type] – This is intended to resolve some of the discussion we had last week about forward compatibility among 1.x versions of this specification.

=== 20 min: Review new draft of VC portion of specification

I've drafted a completely new description of the VC portion of the specification and would to review this with the group. Relevant links:

* [line-through]#link:https://github.com/creator-assertions/identity-assertion/pull/60[PR #60]# – Original version of VC portion of specification. I'm proposing to discard this draft.
* link:https://github.com/creator-assertions/identity-assertion/pull/85[PR #85] – Proposed new version of VC portion of specification.
* link:++https://creator-assertions.github.io/identity/1.x-add-vc-v2/#_w3c_verifiable_credentials++[Rendered version of PR #85]

=== 5 min: Update on Rust early-adopters code

For those who would like to experiment with the identity assertion in code, feel free to follow link:https://github.com/scouten-adobe/cawg-identity-core[scouten-adobe / cawg-identity-core]. Not usable yet, but close. Hoping to have something viable later today or mid-week at worst.

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
