= 09 September 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== 10 min: Review previous action items

Action items from last two meetings:

* *ACTION:* Eric to revise PR 162 to include some consideration of localization and possibly a definition of user-visible string. *NOT DONE, CARRY OVER*
* *ACTION:* Liviu and Eric to do further coding / research work to describe what the `proof` data structure should look like in this case. *NOT DONE* (De-prioritize given shift to identity claim aggregation?)
* *ACTION:* Pam to discuss CBOR signing proposal with Microsoft engineering team and report back next week. *NO UPDATE, CARRY OVER*
* *ACTION:* Eric to explore whether we can reuse the COSE protected header mechanism for RFC 3161 timestamping in the VC approach. *NO UPDATE, CARRY OVER*
* *ACTION:* Eli to submit a PR adding support for K-256 signatures in CAWG. Group to discuss once available.
* *ACTION (✅):* David to propose new wording to encompass full-fledged verifiable credential issuers in addition to observed authentication to social media and similar sites.
* *ACTION (✅):* Jacques to propose new wording to express that the trust decision still remains in the hands of the (human) identity assertion consumer.
* *ACTION (✅):* Eric to close PR 168 without merging.
* *ACTION (✅):* Eric to merge PR 169.
* *ACTION (✅):* Eric to draft a PR to change the name from “W3C verifiable credentials” to “Identity claim aggregation” as described.

=== 10 min: Approval for identity assertion 1.0

*MOTION:* As per Community Specification License process link:++https://github.com/creator-assertions/identity-assertion/blob/main/governance.md#4-specification-development-process++[§4: Specification development process], I move to promote the xref:identity:ROOT:index.adoc[] from draft to approved (version 1.0 final) status:

[quote,Community Specification License :: Governance Policy]
____
4.2. Draft. Each Pre-Draft document of a Working Group must first be Approved to become a “Draft Specification.” Once the Working Group approves a document as a Draft Specification, the Draft Specification becomes the basis for all going forward work on that specification.

4.3. Working Group Approval. Once a Working Group believes it has achieved the objectives for its specification as described in the Scope, it will Approve that Draft Specification and progress it to “Approved Specification” status.
____

=== 20 min: Review PR #167: Define VC proofing mechanism

Review link:https://github.com/creator-assertions/identity-assertion/pull/167/files[PR #167: Define VC proofing mechanism].

=== 20 min: Review PR #175: Rename §8.1 to “Identity claim aggregation”

Review link:https://github.com/creator-assertions/identity-assertion/pull/175[PR #175: Rename §8.1 to “Identity claim aggregation”].

Terminology question TO DISCUSS:

> We use the terms “identity claim aggregation” and “creator identity assertion credential” to mean essentially the same thing. Can we unify on one term? If so, which one?

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
