= 03 September 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== [line-through]#5 min: Review previous action items#

Will resume next week.

=== Update on identity assertion 1.0

=== Retract HTTPS API?

Consider retracting link:https://github.com/creator-assertions/identity-assertion/pull/168[PR #168: Define HTTPS API for identity assertion signing services].

=== Review PR# 169: Define identity provider

Review link:https://github.com/creator-assertions/identity-assertion/pull/169[PR #169: Define identity provider].

=== Proposed change of focus to identity assertion 1.x (VC)

=== Update on CAWG web site

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
