= 20 February 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

Note that meeting details that were previously published on this site are no longer valid.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review

=== 20 min: Introductions / why we're here

Round-table discussion: Attendees describe their affiliations and what they are hoping to accomplish through the CAWG.

=== 5 min: Motion to approve draft status

As per [ยง4: Specification development process](https://github.com/creator-assertions/identity-assertion/blob/main/governance.md#4-specification-development-process), motion to promote identity assertion from pre-draft to draft status.

=== 45 min: Review and prioritize TO DO items in existing draft specifications

== Decisions

== Action items
