= 29 April 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== 15 min: Define named actor’s role

Walk through link:https://github.com/creator-assertions/identity-assertion/pull/98[PR #98: Introduce an optional `signer_payload.role` field].

=== 5 min: Discuss “multiple step processing” issue

Walk through link:https://github.com/creator-assertions/identity-assertion/issue/63[issue #63: Possible interaction in “multiple step processing”]. Close or discuss any needed action items.

=== 35 min: Discuss trust and threat model PR

Walk through link:https://github.com/creator-assertions/identity-assertion/pull/99[PR #99: Define identity assertion trust model], which also includes formal descriptions of prior issue discussions on _threat_ models.

=== 5 min: Discuss overview section PR

Walk thorugh link:https://github.com/creator-assertions/identity-assertion/pull/102[PR #102: Clarify identity assertion “Overview” section].

=== 15 min: Discuss security model PR

Walk through link:https://github.com/creator-assertions/identity-assertion/pull/96[PR #96: Signer payload fixes].

IMPORTANT: Some key participants in the substance of this discussion are not able to join today’s meeting, so this will be a discussion, but not a resolution of this issue.

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
