= 22 April 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== 20 min: IIW readout and discussion

=== 30 min: Discussion on signer payload fixes PR

Walk through [PR #96: Signer payload fixes](https://github.com/creator-assertions/identity-assertion/pull/96) and discuss potential updates to it.

=== 25 min: Discuss remaining issues for 1.0 specification

Walk through [Open issues for 1.0 milestone](https://github.com/creator-assertions/identity-assertion/milestone/1) and explore how to resolve those issues.

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
