= 04 November 2024

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== IIW readout

=== Review PR #197: New introduction to identity claims aggregation

Review link:https://github.com/creator-assertions/identity-assertion/pull/197[PR #197: New introduction to identity claims aggregation].

=== Governance

=== Review issue #3: Schema and example are inconsistent

Review TDM link:https://github.com/creator-assertions/training-and-data-mining-assertion/issues/3[issue #3: Schema and example are inconsistent].

=== Support VC DM 1.1?

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
