= 03 November 2025

https://us02web.zoom.us/rec/share/lteH2ZtVltjceRpQdH24xbMOo9V2zVEelXC-X8oFlnvYwLnkE2tp7sAEjEaHFOZF.pLbiJE_owNf4eDfd[Meeting recording] (1h23m)

== Attendees

* Andrew Dworschak, Yakoa
* Andy Rosen, Sequence Key
* Charlie Halford, BBC
* David Oliver, Guardian Project
* Eric Scouten, Adobe
* Erik Passoja, SAG/AFTRA
* Gavin Peacock, Adobe
* Jenny Pretz, DDEX/RIAA
* Jeremy Uzan, Universal Music
* John Collomosse, Adobe
* Judith Fleenor
* Luke Nispel, OriginVault
* Nathan Freitas, ProofMode
* Nigel Earnshaw, BBC
* Peleus Uhley, Adobe
* Philippe Mougin, AFP
* Philippe Rixhon, JPEG Trust
* Richard W. Kroon, EIDR
* Scott Perry, Digital Governance Institute
* Utkarsh Sharma, Vlinder
* Victor Grey, JLINC
* Will Kreth, HAND (Human & Digital) Identity

== Meeting notes

=== Review previous action items

🎥 _8'56":_ Reviewed action items from previous meetings.

* *ACTION:* Eric to reach out to Wenjing and other ToIP members to build tighter collaboration on agentic identity. -> DONE
* *ACTION:* Eric to explore promotional video ideas. -> DONE. Video recorded; in production now.
* *ACTION:* Andrew to propose updating examples in remainder of metadata asertion spec to match this suggested usage. -> NOT DONE
* *ACTION:* Drummond and Andrew to meet to ensure that FPP and CAWG VC efforts are technically aligned. -> DONE?
* *ACTION:* Eric to edit PR 240 based on feedback from group. -> DONE
* *ACTION:* Eric to edit PR 241 to incorporate feedback from Charlie suggesting that a validator should only display a logo when a certificate is deemed trusted. -> DONE
* *ACTION:* Richard and media identifiers to work toward updating metadata assertion guidance. (Will discuss later in meeting.)

=== Reminder: CAWG Slack channel

🎥 _11'32":_ Reminder that there is a CAWG-specific Slack channel on the DIF Slack. Contact mailto:scouten@adobe.com[Eric Scouten] for details.

=== Heads up: UX guidance draft

🎥 _12'09":_ In next meeting (17 November), Pia will walk us through a proposed UX guidance draft. Available for review here:

* https://github.com/decentralized-identity/cawg-ux-guidance/pull/1[UX guidance PR #1]
* https://cawg.io/ux-guidance/1.0-draft+initial-draft/[Rendered draft]

=== IIW readout

🎥 _12'55":_ Further discussion available on https://ericscouten.dev/2025/iiw41/[Eric's IIW live-blog].

=== Agentic identity workshop readout

🎥 _13'04":_ Discuss Eric's session on agentic identity for content creation and likely outcomes for CAWG.

Tentative theory: Existing model of C2PA claim generator (hardware or software product) and CAWG named actor (human or organization operating said product) holds up well for agentic creations as well. No significant pushback at AIW session.

Key points from discussion:

* From Andrew: There might be a use for some kind of metadata assertion or something like that that outlines exactly what is being delegated, what permissions, what authorizations, what set of actions the person intends to allow the agent to take.
* To what extent do we want to support identity assertions in the case where there is no human in the loop? For now, taking a cautious approach (i.e. we _do_ require a human in the loop).
* Is there a need for a mechanism for the human in the loop to state _what_ they are reviewing? (Possible answers: The entire creative work, or perhaps just a set of edits made by an agent.)
* From Charlie: What about tools like GitHub Copilot, where an agent develops context from the collective actions of the project's contributors? Should the agent sign its work with reference to those contributors?

=== Review PR #240: Add X.509 trust model guidance

🎥 _31'20":_ Reviewed https://github.com/decentralized-identity/cawg-identity-assertion/pull/240[PR #240: Add X.509 trust model guidance].

*ACTION:* Philippe Mougin to coordinate with IPTC to provide the final URLs for the IPTC Origin Verified Publishers trust list. They will be separating into two lists, one for end-entity certs and another for trust anchors.

*ACTION:* Eric to merge PR once final trust list information is provided by IPTC.

=== Review PR #241: Add guidance for display of named actor logo

🎥 _1h01'22":_ Reviewed https://github.com/decentralized-identity/cawg-identity-assertion/pull/241[PR #241: Add guidance for display of named actor logo].

*ACTION:* Eric to update language to state that logo provision applies only to end-entity certificate.

*ACTION:* Peleus to provide language on threat model related to logo display.

=== Identity assertion 1.2 ready to publish?

🎥 _1h11'17":_ Discussed proposal to submit identity assertion 1.2 for WG ratification; move VC integration to 1.3.

*OUTCOME:* Deferred to next meeting to allow requested changes to PR 240 and 241 to be completed.

=== Review draft organizational identity profile

🎥 _1h11'34":_ Discussed proposal for CAWG to publish an organizational identity profile. Available for review here:

* https://github.com/decentralized-identity/cawg-organizational-identity-profile/pull/1[Organizational identity profile PR #1]
* https://cawg.io/organizational-identity-profile/1.0-draft+define-profile/[Rendered version]

*OUTCOME:* Defer ratification until CAWG identity assertion 1.2 is completed.

=== Readout on media identifiers TF work

Deferred to next meeting as key participants were not available at this point in the meeting.
