= 06 January 2025

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== New members introduction

=== Review previous action items

==== From xref:2024/2024-12-16.adoc[] meeting

All PRs updated, issues closed as per previous meeting. PR 203 will be discussed later.

==== From xref:2024/2024-12-03.adoc[] meeting

* *ACTION:* Eric to review current revocation mechanisms and draft a PR describing at least one preferred revocation mechanism. → *DONE:* See PR #204 on today's agenda.
* *ACTION:* Eric to follow up on feedback provided by Phillippe on more concrete examples for how `constrained` might be defined in training and data mining assertion. → *TRACKING:* Filed as link:https://github.com/creator-assertions/training-and-data-mining-assertion/issues/7[issue #7: Provide a better definition of `constrained`].

=== PR #203: Add optional `method` field for describing the technique used to verify account/URI control

Review link:https://github.com/creator-assertions/identity-assertion/pull/203[PR #203: Add optional `method` field for describing the technique used to verify account/URI control].

Since last meeting, minor naming changes have been made.

*TO DISCUSS:* Suggestion from Brian McInnis to link:https://github.com/creator-assertions/identity-assertion/pull/203#discussion_r1889002960[add a `cawg.webauthn`] option.

=== PR #204: Add section on credential status / revocation

Review new link:https://github.com/creator-assertions/identity-assertion/pull/204[PR #204: Add section on credential status / revocation].

=== PR #205: Finalize URI for ICA context and schema

Review new link:https://github.com/creator-assertions/identity-assertion/pull/205[PR #205: Finalize URI for ICA context and schema].

=== Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
