= 05 May 2025

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and membership information.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== Start meeting

* Start recording
* Welcome and W3C IPR reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== New members introduction

=== Reminder: Vote in co-chair election

Ballots should have been sent or will soon be sent and are to be completed by end of day this Friday.

=== Review previous action items

From xref:2025-04-21-na-eu.adoc[] and xref:2025-04-21-apac.adoc[]:

* *ACTION:* Luke to submit a PR adding a JSON-LD context document. -> *DONE* Will discuss later in agenda.
* *ACTION (✅):* Eric to merge the following PRs:
** https://github.com/decentralized-identity/cawg-identity-assertion/pull/227[#227: Consolidate guidance around JSON schema document]
** https://github.com/decentralized-identity/cawg-identity-assertion/pull/228[#228: Add references to JPEG Trust work for ownership and rights declarations]
** https://github.com/decentralized-identity/cawg-identity-assertion/pull/229[#229: Clarify the intent of verifiedAt timestamp]
* *ACTION:* All members to review the following draft specifications and make any objections known prior to 5 May 2025 meeting. -> Will discuss later in agenda.

=== PR #231: Add specific schemas for each VC schema version and JSON-LD context

Review https://github.com/decentralized-identity/cawg-identity-assertion/pull/231[PR #231: Add specific schemas for each VC schema version and JSON-LD context].

=== Issue #225: Link to ToIP technical architecture is broken

Review https://github.com/decentralized-identity/cawg-identity-assertion/issues/225[issue #225: Link to ToIP technical architecture is broken].

=== Issue #174: Review latest draft of VC data model 2.0

Review https://github.com/decentralized-identity/cawg-identity-assertion/issues/174[issue #174: Review latest draft of VC data model 2.0]. Primary question: Any changes to VC DM 2.0 since mid-2024 that might impact our work?

=== Ratification vote: Identity

Decide whether to promote https://cawg.io/identity/1.1-draft/[1.1 draft of identity assertion] to working-group approved status.

=== Ratification vote: Metadata

Decide whether to promote https://cawg.io/metadata/1.1-draft/[1.1 draft of metadata assertion] to working-group approved status.

=== Ratification vote: Training and data mining

Decide whether to promote https://cawg.io/training-and-data-mining/1.1-draft/[1.1 draft of training and data mining assertion] to working-group approved status.
