= 19 May 2025

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and membership information.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== Start meeting

* Welcome and W3C IPR reminder
* Please comment in the chat for attendance

include::partial$upcoming-meeting-changes.adoc[]

=== New members introduction

=== Review previous action items

All proposed revisions to specifications were merged. As requested, three assertion specifications were submitted to DIF Steering Committee for final approval.

=== Co-chair introduction

=== Identity hooks

Andrew Dworschak will give an introduction to identity hooks, a proposal for consistent, private, and extensible identity.

=== Machine / agentic identity

Discuss agentic identity and how/if it may be relevant to future CAWG identity standards.

=== Report-out from media identifiers TF

*Problem space definition:* There are many media industry identifiers that are commonly associated with various individual talent professionals (musicians, actors, directors, etc.) and organizations that should be associated with content that they are involved in producing. Most of these identifiers are not fully-provisioned verifiable identifiers (i.e. they do not have signing keys associated with them) so we rely on metadata providers that are trusted within each industry segment to properly add these identifiers and vouch for their validity.

*Deliverables:* We agreed to the following deliverables:

. A new appendix in an upcoming version of the xref:metadata:ROOT:index.adoc[] specification that:
.. Recommends the adoption of existing IETF-issued namespace and field names for existing metadata. (Specifically avoiding defining new metadata standards within CAWG.)
.. Recommends the use of CAWG identity issuers signed by trusted industry entities to sign the CAWG metadata assertion and attest to the validity of the content therein.
. A new guidance document that discusses common use cases in various industries and demonstrates how the above recommendations would be implemented.

*ACTION:* Eric to prepare initial drafts for the above documents. (In progress.)

*Meeting cadence:* Every Monday, alternating weeks with full CAWG meeting. Next week rescheduled to Wednesday, 28 May, to avoid US Memorial Day holiday.

=== Meeting at Content Authenticity Summit

For those attending the link:https://www.contentauthenticitysummit.com[Content Authenticity Summit] (4 June) or who are already in New York City, we may have an additional in-person meetings on Tuesday or Thursday before or after the summit. Let me know if interested.

=== Review "post-1.1" milestone in GitHub

There are link:https://github.com/decentralized-identity/cawg-identity-assertion/milestone/10[39 open issues] flagged as "post 1.1." Let's discuss and start prioritizing what might be in scope for 1.2.

=== Upcoming meeting conflicts

Eric unavailable to run the following meetings:

* 02 June 2025 (travel to NY) -- Scott will run if enough agenda items
* 23 June 2025 media identifiers (vacation) -- TBD
* 30 June 2025 (vacation) -- Scott will run
