= 10 February 2025 (APAC)

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 5 min: New members introduction

=== 5 min: Review previous action items

All action items from previous meetings resulted in PRs that have been merged.

=== Review PR #211: (Work in progress) Identity claims aggregation validation

Review link:https://github.com/creator-assertions/identity-assertion/pull/211[PR #211]. This is a mostly-complete draft. Not yet ready to merge, but looking for group feedback on what has been written so far.

=== Review PR #210: Introduce new section, “C2PA Manifest validation prerequisites”

Review link:https://github.com/creator-assertions/identity-assertion/pull/210[PR #210]. This PR calls out the C2PA Manifest validation as a prerequisite for identity assertion validation. Adds two new constraints:

* The C2PA Manifest must now have been found to be _valid._ (The 1.0 CAWG spec only required well-formed.)
* The identity assertion must have been found to match the hash reference in the claim data structure.

=== Review PR #207: Limit validity period for identity claims verifications

Review link:https://github.com/creator-assertions/identity-assertion/pull/207[PR #207]. No new language as yet, but I'd like to explore the idea from a previous meeting of declaring the lifetime of identity claims verifications.

=== 5 min: Closing and review

Invitation to subsequent meetings, which will typically be on Mondays.
