= 25 August 2025

https://us02web.zoom.us/rec/share/r7L1wQy3cUlwDAHdPwo9PxGfBFECqPpqVlS4B7MeF7Ov2qiX5x0soZiaTZc1cYu2.F5ROMrtzsqoeOC6d[Meeting recording] (1h30m)

== Attendees

* Andrew Dworschak, Yakoa
* Andy Rosen, Sequence Key
* Colin Murphy, Adobe
* David Oliver, Guardian Project
* Drummond Reed, First Person Project
* Eric Scouten, Adobe
* Erik Passoja, SAG/AFTRA
* Gavin Peacock, Adobe
* Jeremy Uzan, Universal Music
* Karla McKenna, GLEIF
* Luke Nispel, OriginVault
* Makki Elfatih, HKDolts
* Nathan Freitas, ProofMode
* Nicholas Salvemini, Adobe
* Peleus Uhley, Adobe
* Philippe Mougin, AFP
* Richard W. Kroon, EIDR
* Santiago Lyon, Adobe
* Scott Jones, RealEyes
* Scott Perry, Digital Governance Institute
* Tim Cappalli, Okta
* Victor Grey, JLINC
* Will Kreth, HAND (Human & Digital) Identity

== Meeting notes

=== New members introduction

* 🎥 _9'04":_ David Oliver, Guardian Project

=== Review previous action items

🎥 _9'46":_ Reviewed previous action items.

* *ACTION:* Eric to reach out to Wenjing and other ToIP members to build tighter collaboration on agentic identity. -> UNDERWAY. No new developments.
* *ACTION:* Eric to explore promotional video ideas. -> UNDERWAY. Working with Adobe team to build a new 1-2 minute video that we can use on site. ETA ~~late August~~ -> early September.
* *ACTION:* Scott to work up initial draft text to use on CAWG home page. -> DONE. Eric to include on new site.
* *ACTION (✅):* Eric to review PR #238 further with Leonard, Nigel, and Andrew. -> DONE. Will review today.
* *ACTION (✅):* Eric to review further with Andy and Noga (original author of this section). -> Still pending.
* *ACTION:* Luke to revise endorsement PR #11 to incorporate suggestions from Andrew's presentation.

=== CAI meeting

🎥 _11'14":_ 27 August (9am US Pacific / noon US Eastern / 1600 UTC) CAI lunch and learn event. Details at

=== Identity assertion PR #238: Update referenced assertions requirements

🎥 _12:48":_ Reviewed https://github.com/decentralized-identity/cawg-identity-assertion/pull/238[PR #238: Update referenced assertions requirements].

This PR is foundational to some of the work recently presented by Andrew. Brought back for re-review after discussions to address some of the concerns raised in previous meeting.

*ACTION (✅):* Eric to merge PR with edits as made during meeting.

=== Metadata assertion PR #5: Add media identifiers guidance

🎥 _12:48":_ Preliminary review of https://github.com/decentralized-identity/cawg-metadata-assertion/pull/5[PR #5: Add media identifiers guidance].

Not ready to merge yet (a few to-do items), but want the larger group to know where media identifiers TF is headed.

*ACTION (✅):* Eric to revise based on feedback in CAWG meeting.
*ACTION:* Referred back to media identifiers TF to finalize wording and fill in TO DO items.
*ACTION:* Andrew to propose updating examples in remainder of spec to match this suggested usage.
*ACTION:* Eric to revise wording to encourage use of human-language and URN-based identifiers.

=== Metadata assertion PR #9: Add a section recommending a user experience warning about unattributed metadata

🎥 _33:17":_ Reviewed https://github.com/decentralized-identity/cawg-metadata-assertion/pull/9[PR #9: Add a section recommending a user experience warning about unattributed metadata].

Concerns raised about the existence of unattributed metadata in the system.

=== Update from First Person project

🎥 _43:29":_ Drummond gave an update on the First Person Project, which will soon be spun up as the Decentralized Trust Graph Working Group within Trust Over IP Foundation. FPP aims to solve proof of personhood without using a global biometric database. He explained two types of verifiable digital credentials: personal credentials and verifiable relationship credentials. The project uses zero-knowledge proofs to provide strong proof of personhood while supporting anonymity when needed. Drummond also discussed the concept of privacy-preserving personas and the anatomy of a digital wallet that supports first-person credentials. The presentation concluded with an explanation of how personal credentials and verifiable relationships create a trust triangle, strengthening the trust signal through zero-knowledge proofs.

*ACTION:* Drummond and Andrew to meet to ensure that FPP and CAWG VC efforts are technically aligned.

=== Forward permissions credential

🎥 _56:44":_ Luke presented updates on the forward permissions credential, which aims to address confusion about the existing endorsement assertion between social proof/reviews and permission delegation.

*ACTION:* Luke to track work on identity assertion 1.2 and re-present this proposal when identity 1.2 matures further.

=== Identity assertion issue triage

🎥 _1h01:53":_ Reviewed the https://github.com/decentralized-identity/cawg-identity-assertion/issues[39 open issues against identity assertion].

=== Open issues for training and data mining assertion

🎥 _1h09:38":_ Reviewed link:https://github.com/decentralized-identity/cawg-training-and-data-mining-assertion/issues[five open issues] against training and data mining assertion.

Deferred action on these until further guidance about upcoming IETF work on training intent is solidified.
