= 27 January 2025

Please see xref:ROOT:index.adoc#_meeting_schedule[Meeting schedule] for schedule information and to request an invitation.

== Meeting recording

A link to the meeting recording will be provided after the meeting.

== Attendees

== Agenda

=== 5 min: Start meeting

* Start recording
* Welcome and community specification license reminder
* Agenda review and call for agenda items

include::partial$upcoming-meeting-changes.adoc[]

=== 20 min: Introduction

This being the first APAC meeting; all members are new.

=== 30 min: Recap of CAWG's first year

Eric will present a description of CAWG's work so far and how it fits into the overall C2PA and content provenance ecosystem.

=== 10 min: Review PR #207: Limit validity period for identity claims verifications

Review link:https://github.com/creator-assertions/identity-assertion/pull/207[PR #207].

=== 5 min: Meeting cadence

Proposal: Alternate weekly meetings between NA/EU and APAC time slots.

Explore what times work well for APAC and how that might shift as US enters daylight savings (summer) time zone in March. (What TZ shifts do we need to consider, especially for Australia?)
