= 27 January 2025

https://youtu.be/yZk2qUKvkSI[Meeting recording]

== Attendees

* Alex Tweeddale, Cheqd
* Andrew Dworschak, Yakoa
* Andy Rosen, Sequence Key
* Drummond Reed, Gen Digital
* Eric Scouten, Adobe
* Jeremy Uzan, Universal Music
* John Phillips, Sezoo
* Peleus Uhley, Adobe
* Scott Perry, Digital Governance Institute
* Victor Grey, JLINC

== Meeting notes

=== Introductions

This being the first APAC meeting, we all introduced ourselves to each other:

* 🎥 _1'24":_ Eric Scouten, Adobe
* 🎥 _1'56":_ Alex Tweeddale, Cheqd
* 🎥 _2'23":_ Andrew Dworschak, Yakoa
* 🎥 _3'07":_ Andy Rosen, Sequence Key
* 🎥 _3'41":_ Victor Grey, JLINC
* 🎥 _4'33":_ Jeremy Uzan, Universal Music
* 🎥 _5'05":_ John Phillips, Sezoo
* 🎥 _5'45":_ Peleus Uhley, Adobe

=== Recap of CAWG's first year

🎥 _6'59":_ Eric presented a recap of the work done so far by the Creator Assertions Working Group, including the C2PA data model and the identity assertion framework.

xref:attachment$2025-01-27/c2pa-cawg-walkthrough.pdf[Slide deck (PDF)]

This recap is also available as a standalone video:

link:https://youtu.be/OtoFyDMo0zs[January 2025 Introduction to CAWG (YouTube, 40min)]

=== Demo of creds.xyz

🎥 _1h00'20":_ Alex demonstrated link:https://creds.xyz[creds.xyz], a product that aggregates credentials from various sources and creates verifiable presentations, exploring its potential integration with the identity assertion framework. The group agreed that creds.xyz performs a role that is very similar to that described by identity claims aggregation and to further explore a possible integration.

=== Review PR #207: Limit validity period for identity claims verifications

🎥 _1h03'36":_ Reviewed link:https://github.com/creator-assertions/identity-assertion/pull/207[PR #207].

Similar to the discussion in link:++https://cawg.io/meeting-notes/2025-01-21/#_review_pr_207_limit_validity_period_for_identity_claims_verifications++[last week's meeting], the group agreed that:

* The proposal in PR 207 is too arbitrary and needs to be refined. Some identity signals may reasonably be held for longer times than others.
* A possible answer is for the identity claims aggregator to provide information about its intended validation lifetime to:
** The named actor at time of verification. (How long will this information be retained?)
** The identity aggregation _consumer_ at time of validation. (When will the ICA request a renewal?)

=== Meeting cadence

The group agreed to alternating biweekly meetings between NA/EU and APAC.

Eric will announce details of that schedule transition shortly.
