= 21 April 2025 (APAC)

https://us02web.zoom.us/rec/share/Phmv4Mmt-qjCRG4GSDYcPOG9q4crqjmy73Cf75jMTDJzvkInh_7NKk5ZJcNbqRYe.JPmrKMPMywF1KNSI[Meeting recording] (47m)

== Attendees

* Alex Tweeddale, Cheqd
* Drummond Reed, Gen Digital
* Eric Scouten, Adobe
* Judith Fleenor
* Peleus Uhley, Adobe

== Meeting notes

=== Review previous action items

🎥 _5'29":_ From xref:2025-03-24-na-eu.adoc[]:

*ACTION:* Eric agreed to add a note to PR 211 clarifying that if a validator stops processing at the first failure, there may be other undetected failures. -> *Discussed and decided we don't need this.*

*ACTION (✅):* Eric, Otto, and Juan to discuss merging language with Otto’s proposal in #223. Once we’ve agreed, approved to merge this PR. -> *DONE*

*ACTION (✅):* Eric to merge PR 219.

*ACTION:* Luke to submit a PR adding a JSON-LD context document. -> ?

*ACTION (✅):* Eric to work with Kim and Juan to determine the co-chair election process. -> *DONE*

*ACTION (✅):* Eric and Andrew to arrange a 1:1 meeting to follow up on identity hooks. -> *DONE* (See also Andrew's IIW talk when proceedings are available.)

=== Discuss issue #216: Identity hooks

🎥 _6'27":_ Long discussion about Andrew Dworschak's proposal for identity hooks. Andrew has provided a solid introduction to the concept in link:https://github.com/decentralized-identity/cawg-identity-assertion/issues/216[issue #216].

=== Discuss issue #212: Self-signing credentials

🎥 _13'30":_ Discussion about Alex Tweeddale's proposal for enabling named actors to sign identity assertions on their own behalf. See detailed proposal in link:https://github.com/decentralized-identity/cawg-identity-assertion/issues/212[issue #212].

New discussion about whether verifiable presentations could be used to augment the existing identity claims aggregation model.

=== Review PR #227: Consolidate guidance around JSON schema document

🎥 _27'24":_ Reviewed link:https://github.com/decentralized-identity/cawg-identity-assertion/pull/227[PR #227: Consolidate guidance around JSON schema document].

*ACTION (✅):* Eric to merge (already approved in NA/EU meeting).

=== Review PR #228: Add references to JPEG Trust work for ownership and rights declarations

🎥 _28'51":_ Reviewed link:https://github.com/decentralized-identity/cawg-identity-assertion/pull/228[PR #228: Add references to JPEG Trust work for ownership and rights declarations]. Wording suggested by Phillippe Rixhon.

*ACTION (✅):* Eric to merge (already approved in NA/EU meeting).

=== Review PR #229: Clarify the intent of verifiedAt timestamp

🎥 _29'40":_ Reviewed link:https://github.com/decentralized-identity/cawg-identity-assertion/pull/229[PR #229: Clarify the intent of verifiedAt timestamp].

*ACTION (✅):* Eric to merge (already approved in NA/EU meeting).

=== Intent to submit for working group approval

🎥 _30'44":_ *ACTION:* All members to review the following draft specifications and make any objections known prior to 5 May 2025 meeting. Highlights of changes since the previous ratified versions of each are called out here:

* link:https://cawg.io/identity/1.1-draft/[Identity assertion, 1.1-draft]
** Added link:https://cawg.io/identity/1.1-draft/#_identity_claims_aggregation[Identity claims aggregation]
** Transition to DIF licensing and governance
* link:https://cawg.io/metadata/1.1-draft/[Metadata assertion, 1.1-draft]
** Transition to DIF licensing and governance
* link:https://cawg.io/training-and-data-mining/1.1-draft/[Training and data mining assertion, 1.1-draft]
** Fixed an inconsistency between schema and example
** Transition to DIF licensing and governance

NOTE: Not currently calling for WG approval on endorsement assertion. Consider archiving this spec for lack of interest?

NOTE: Intent to reformat Asciidoc, having learned some best practices.

=== Media identifiers subgroup

🎥 _32'18":_ Call for members and getting started. (And apologies for not having done so already.)

=== Co-chair election

🎥 _32'49":_ *Process proposal:* After today's meeting, we will open an election for one co-chair position (to serve alongside Eric Scouten). In the event there are multiple candidates, we will choose the candidate by link:https://opavote.com/methods/instant-runoff-voting#san-francisco-rcv[San Francisco-style ranked choice voting]. The election will be open for seven calendar days and the new co-chair will serve starting with the next meeting on 7 May.

Open floor for candidates to self-nominate.

* 🎥 _33'34":_ Alex Tweeddale

=== Brainstorm identity 1.2

🎥 _34'44":_ What should be on our radar once we complete identity assertion 1.1?

Largely a recap of discussion from NA/EU meeting. Some new items:

* Can we generalize the identity claims aggregator mdoel to include self-custody of identity signals?
* Agreed on emphasis for privacy-preserving credentials with subsequent selective or additive disclosure.
