= 29 June 2026

https://us02web.zoom.us/rec/share/BDzOvwP8qkNyPTAGnOH9Vurheo9bzZNu7bKXi-I6jasoP3VYlabCpbPLV15p6hRl.Wo3IONGihfq9Gim1[Meeting recording] (2h06m)

== Attendees

* Andy Rosen, Sequence Key
* Bill Huang, Trufo
* Bruce MacCormack
* Dom Guinard, SSL.com
* Drummond Reed
* Erik Passoja, SAG/AFTRA
* Grace Rachmany, DIF
* Jenny Pretz, DDEX/RIAA
* Joe Grinstead, Pixlmob
* Karla McKenna, GLEIF
* Makki Elfatih, HKDolts
* Matthew Rappard, Cognitive Proof
* Nathan Freitas, ProofMode
* Niels Rump, DDEX
* Peleus Uhley, Adobe
* Richard W. Kroon, EIDR
* Scott Perry, Digital Governance Institute
* Vasily Suvorov, accelerate.swiss
* Will Kreth, HAND (Human & Digital) Identity

NOTE: Attendance info might be incomplete. Based on those who spoke either in audio or chat this week.

== Meeting notes

=== New members introduction

* 🎥 _13'25":_ Matthew Rappard, Cognitive Proof

=== Review previous action items

🎥 _15'09":_

*ACTION:* Eric to draft a new `cawg.actions` assertion spec. -> Eric and Charlie to meet later in the week. -> DONE: Eric and Leonard to coordinate response between CAWG and C2PA.

*ACTION:* Eric to re-review PR 265 (Rewrite X.509 validation section). -> DONE (will discuss later)

*ACTION:* Eric to merge PR 264 (archive-quality identifier). -> DONE

*ACTION:* Eric to add more time in agenda to review definitions in detail. -> DONE (will discuss later)

=== Readout from trust task force: Scott

🎥 _17'48":_ Trust TF is making progress on adding governance hooks or additional claims hooks within the identity assertion, one being the trust registry hook based on Trust Over IP's Trust Registry Query Protocol and establishing a long-term plan for governing identity credential issuance.

=== Readout from discussion with W3C VC group: Scott

🎥 _21'45":_ Scott working to establish a relationship with W3C Verifiable Credentials Group. Scott and Eric will be presenting on 22 July.

=== Readout from consent task force: Erik

🎥 _24'09":_ Erik working with Eric to convert consent assertion to Asciidoc and have it ready for full CAWG meeting. Meetings suspended unless additional work identified.

*ACTION:* Eric to prepare Asciidoc site.

=== CAWG x UX task force: Matthew

🎥 _28'01":_ Spinning up CAWG UX task force. Request from Andy Rosen to have more media industry representation in UX TF.

=== Where to focus attention?

🎥 _32'04":_ Richard draws attention to a letter being drafted by media industry leadership asking that the focus be moved from C2PA to CAWG as the primary consumer-facing specification. Concern raised that CAWG requires C2PA, but C2PA doesn't require CAWG. CAWG members generally welcoming the recognition that the identities of content creators and persons depicted in content are important parts of the overall provenance story.

=== Readout from vLEI task force: Vasily

🎥 _1h06'45":_ First draft of vLEI credential spec available in GitHub.

=== Definition of terms: Erik

🎥 _1h08'57":_ Based on recent discussion, have split the definition of "creator" into two terms: "content creator" and "asset creator." Still awaiting feedback from review of other similar definitions in other standards.

=== Review/triage new issues

=== AOB
