= 04 May 2026

https://us02web.zoom.us/rec/share/UBn5UX2lu26F8Xkk9QRh6a_z45YNGNEknovNcW-f_fyBGh71vTfiorHjXG2DrA9j.m8HsOR4qHtfIBNyg[Meeting recording] (1h32m)

== Attendees

* Andrew Dworschak, Yakoa
* Andy Rosen, Sequence Key
* Bill Huang, Trufo
* Bruce MacCormack
* Dom Guinard, SSL.com
* Erik Passoja, SAG/AFTRA
* Grace Rachmany, DIF
* Jenny Pretz, RIAA
* Jeremy Uzan, Universal Music
* Nathan Freitas, ProofMode
* Nicholas Salvemini, Adobe
* Philippe Rixhon, JPEG Trust
* Scott Perry, Digital Governance Institute
* Vasily Suvorov, accelerate.swiss

NOTE: Attendance info might be incomplete. Based on those who spoke either in audio or chat this week.

== Meeting notesw

=== IIW readout: Scott

🎥 _13'07":_ Scott and Eric gave three CAWG-related sessions at IIW last week:

* Introduction to C2PA and CAWG
* Governance assertion
* Archival-quality identifiers

SEDI (Utah-led State Endorsed Digital Identity) was one of the big hot topics.

https://originator-profile.org/en-US/about/[Originator Profile project], which seems adjacent to C2PA and CAWG, though technically distinct, made several presentations. The subtle differences are that they are more focused on the news industry and on certifying the authenticity and provenance of both text and media on a news-oriented web site. Well-entrenched among Japanese news media; not aware of much reach outside of Japan.

Bruce mentioned that there is an IPTC-hosted summit in Japan in October, where C2PA and CAWG will be highlighted.

=== Readout from trust task force: Scott

🎥 _27'33":_ Scott prepared a slide deck for the proposed governance assertion, highlighting that we could identify the endorsement of a governing authority into a claim made by an individual or organization.

=== Readout from VC/VP task force: Andrew

🎥 _31'24":_ Working through how VC/VP has to depart from the existing identity claims aggregation spec, especially in some interesting edge cases where an identity assertion might itself aggregate multiple VCs.

=== Readout from consent task force: Erik

🎥 _38'55":_ Debate about where the boundaries are between CAWG and JPEG Trust with regards to rights declarations. Working through definitions of various kinds of consent related to content and which are in-scope for the current draft specification.

=== Proposed KERI/ACDC task force: Vasily

🎥 _42'28":_ Vasily working to spin up the KERI/ACDC task force. Vasily gave a quick overview of what ACDCs and VLEIs are, including the GLEIF/VLEI governance model.

=== Review identity assertion PR #72: Emphasizing the use of REGISTERED spots in the advertising use case

🎥 _55'50":_ Review identity assertion https://github.com/decentralized-identity/cawg-identity-assertion/pull/72/changes[PR #72: Emphasizing the use of REGISTERED spots in the advertising use case].

Andy asked that we continue to defer this.

=== Questions about who is signing in the C2PA and CAWG ecosystem.

🎥 _59'30":_ Phillippe raised a number of questions about who is involved in the signing process of a C2PA manifest and CAWG identity assertion and what legal standing they may have in various jurisdictions. This question evolved into a discussion about agentic identity and how it relates to human identity in the CAWG ecosystem.

=== Questions about who is signing in the C2PA and CAWG ecosystem

🎥 _1h12'49":_ Richard provided a heads up that there is a discussion group going on amongst members of
commercial or professional music, entertainment, advertising, and news drafting an open letter that will be submitted to C2PA and CAWG reiterating what Bruce said in the previous meeting's readout on the IPTC Provenance Summit that C2PA alone is insufficient for the use cases that are important to these industries. This highlights a potential gap in that CAWG doesn't have its own conformance regime.
