= Contributing

== Governance

Each of the projects of the Creator Assertion Working Group are licensed and governed under the link:https://github.com/CommunitySpecification/1.0[Community Specification License 1.0]. In order to contribute to the specifications or the working group meetings, you will first need to sign the contributor license agreement. The process for this is separate for each CAWG project and described in the README document for each repository.

Each project contains a scope document (see scope.md at the root of each repository) which describes the intended purpose of the project.

== Code of conduct

Each of the projects of the Creator Assertions Working Group are covered by a code of conduct adapted from the Contributor Covenant Code of Conduct. This code of conduct describes standards for acceptable and unacceptable behavior and policies for enforcing those standards. As an example, see the link:https://github.com/creator-assertions/identity-assertion/blob/main/code-of-conduct.md[Code of Conduct] in the Identity Assertion project. All projects follow this same code of conduct.

== Meeting schedule

