= Creator Assertions Working Group

The Creator Assertions Working Group builds upon the work of the link:https://c2pa.org:[Coalition for Content Provenance and Authenticity] (C2PA) by defining additional assertions that allow content creators to express individual and organizational intent about their content.

(See link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_technical_overview++[C2PA Technical Specification: Technical Overview] for an explanation of the C2PA data model including assertions.)

== Technical specifications

These assertions are specified by the following documents:

* xref:identity:ROOT:index.adoc[]
* xref:endorsement:ROOT:index.adoc[]
* xref:metadata:ROOT:index.adoc[]
* xref:training-and-data-mining:ROOT:index.adoc[]

== CAWG is joining DIF!

As of March 2025, CAWG is becoming a working group of the link:https://identity.foundation[Decentralized Identity Foundation (DIF)]. Please see their link:https://blog.identity.foundation/welcome-cawg/[blog article welcoming us]. The blog article contains a short sign-up form that will help you join and gain access to CAWG meetings.

== Contributing

=== Governance

Each of the projects of the Creator Assertion Working Group are licensed and governed under the link:https://github.com/CommunitySpecification/1.0[Community Specification License 1.0]. In order to contribute to the specifications or the working group meetings, you will first need to sign the contributor license agreement. The process for this is separate for each CAWG project and described in the README document for each repository.

Each project contains a scope document (see `scope.md` at the root of each repository) which describes the intended purpose of the project.

=== Code of conduct

Each of the projects of the Creator Assertions Working Group are covered by a code of conduct adapted from the link:https://www.contributor-covenant.org[Contributor Covenant Code of Conduct]. This code of conduct describes standards for acceptable and unacceptable behavior and policies for enforcing those standards. As an example, see the link:https://github.com/creator-assertions/identity-assertion/blob/main/code-of-conduct.md[Code of Conduct] in the Identity Assertion project. All projects follow this same code of conduct.

=== Meeting schedule

The Creator Assertions Working Group holds video meetings every other Monday at two times:

*North America / Europe:*

* 0800 US Pacific
* 1100 US Eastern
* 1500 UTC
* 1600 Central Europe

*APAC:*

* 1800 US Pacific
* 0100 (Tuesday) UTC
* 0630 India
* 1200 Sydney

The same agenda is prepared for both meetings and the meetings are scheduled for 90 minutes each.

To read about it, read link: https://blog.identity.foundation/welcome-cawg/[blog article welcoming CAWG into DIF].

=== Joining
1. Sign IPR Forms
  - Are you already a DIF Member?
    - If Yes: You're in
    - If No: Are you a ToIP Member or CAWG Signatory?
      - If Yes:
        - Are you full-time employed or representing a company?  link:https://bit.ly/DIF-contributor[Sign the “Contributor” agreement]
        - Otherwise: link:https://bit.ly/DIF-feedback-agreement[Sign the “Feedback Engagement” agreement]
      - If No:
        - link:https://identity.foundation/join/[Join DIF]
2. Join DIF Communication Channels
  - link:https://lists.identity.foundation/g/cawg[Join DIF Slack] and introduce yourself in the #wg-cawg channel.
  - link:https://lists.identity.foundation/g/cawg[Join CAWG Mailing List]
    - Mailing List Link: Subscribe to receive updates, meeting notes, and important discussions via email.
3. Ask in one of the communication channels to be added to the calendar



include::meeting-notes:partial$upcoming-meeting-changes.adoc[]

=== Meeting notes

Meeting notes and agendas for upcoming meetings are published xref:meeting-notes:index.adoc[here].
