= Creator Assertions Working Group

The Creator Assertions Working Group builds upon the work of the link:https://c2pa.org:[Coalition for Content Provenance and Authenticity] (C2PA) by defining additional assertions that allow content creators to express individual and organizational intent about their content.

(See link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_technical_overview++[C2PA Technical Specification: Technical Overview] for an explanation of the C2PA data model including assertions.)

== Technical specifications

These assertions are specified by the following documents:

* xref:identity:ROOT:index.adoc[]
* xref:endorsement:ROOT:index.adoc[]
* xref:metadata:ROOT:index.adoc[]
* xref:training-and-data-mining:ROOT:index.adoc[]

== CAWG is joining DIF!

As of March 2025, CAWG is becoming a working group of the link:https://identity.foundation[Decentralized Identity Foundation (DIF)]. Please see their link:https://blog.identity.foundation/welcome-cawg/[blog article welcoming us]. The blog article contains a short sign-up form that will help you join and gain access to CAWG meetings.

== Contributing

=== Governance

Each of the projects of the Creator Assertion Working Group are licensed and governed under the link:http://www.w3.org/Consortium/Patent-Policy-20040205[W3C Patent Policy]. In order to contribute to the specifications or the working group meetings, you will first need to sign the appropriate agreement:

- **If you're already a DIF Member**, no further steps needed
- **If you're an Unaffiliated Individual**: Sign the link:https://bit.ly/DIF-feedback-agreement[DIF Feedback Agreement] and select "Creator Assertions" WG
- **If you're not a DIF Member, participating on behalf of an Organization**:
    - If you'd like to join DIF, link:https://identity.foundation/join/[start here] or contact us at membership@identity.foundation
    - If you're a member of ToIP or have previously signed the CAWG CLA (see section 3 in the link:https://github.com/decentralized-identity/org/blob/main/Org%20documents/WG%20documents/DIF_CAWG_WG_Operating_Addendum_v1.pdf[Operating Addendum] for the latest list of organizations):
        - Sign the link:https://bit.ly/DIF-contributor[DIF Contributor Agreement]
    - If you have questions, email membership@identity.foundation

Each project contains a scope document (see `scope.md` at the root of each repository) which describes the intended purpose of the project.

=== Code of conduct

We are committed to providing a welcoming and inspiring community for all. Please read and understand link:https://github.com/decentralized-identity/org/blob/master/code-of-conduct.md[DIF's Code of Conduct] before participating in this project.

=== Meeting schedule

The Creator Assertions Working Group holds video meetings every other Monday at two times:

*North America / Europe:*

* 0800 US Pacific
* 1100 US Eastern
* 1500 UTC
* 1600 Central Europe

*APAC:*

* 1800 US Pacific
* 0100 (Tuesday) UTC
* 0630 India
* 1200 Sydney

The same agenda is prepared for both meetings and the meetings are scheduled for 90 minutes each.

To request an invitation, please view the link:https://blog.identity.foundation/welcome-cawg/[blog article welcoming CAWG into DIF]. The article contains a short sign-up form that will help you join and gain access to CAWG meetings and the mailing list.

include::meeting-notes:partial$upcoming-meeting-changes.adoc[]

=== Meeting notes

Meeting notes and agendas for upcoming meetings are published xref:meeting-notes:index.adoc[here].
