= Creator Assertions Working Group

The Creator Assertions Working Group builds upon the work of the link:https://c2pa.org:[Coalition for Content Provenance and Authenticity] (C2PA) by defining additional assertions that allow content creators to express individual and organizational intent about their content.

(See link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_technical_overview++[C2PA Technical Specification: Technical Overview] for an explanation of the C2PA data model including assertions.)

== Technical specifications

These assertions are specified by the following documents:

* xref:identity:ROOT:index.adoc[]
* xref:endorsement:ROOT:index.adoc[]
* xref:metadata:ROOT:index.adoc[]
* xref:training-and-data-mining:ROOT:index.adoc[]

== Contributing

As of March 2025, CAWG has become a working group within the link:https://identity.foundation[Decentralized Identity Foundation (DIF)]. Please see their link:https://blog.identity.foundation/welcome-cawg/[blog article welcoming us].

To participate in CAWG or attend our meetings, you will need to link:https://identity.foundation/join/[join DIF] at least at the contributor level.

=== Meeting schedule

The Creator Assertions Working Group holds video meetings every other Monday at two times:

*North America / Europe:*

* 0800 US Pacific
* 1100 US Eastern
* 1500 UTC
* 1600 Central Europe

*APAC:*

* 1800 US Pacific
* 0100 (Tuesday) UTC
* 0630 India
* 1200 Sydney

The same agenda is prepared for both meetings and the meetings are scheduled for 90 minutes each.

To request an invitation, please view the link:https://blog.identity.foundation/welcome-cawg/[blog article welcoming CAWG into DIF]. The article contains a short sign-up form that will help you join and gain access to CAWG meetings and the mailing list.

include::meeting-notes:partial$upcoming-meeting-changes.adoc[]

=== Meeting notes

Meeting notes and agendas for upcoming meetings are published xref:meeting-notes:index.adoc[here].
