name: Cleanup Preview

on:
  pull_request:
    types: [closed]
    workflow_dispatch:

permissions:
  deployments: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Delete deployment environment and comment
      run: |
        node .github/scripts/cleanup-preview.js

