name: Cleanup Preview

on:
  pull_request:
    types: [closed]

permissions:
  deployments: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Delete deployment environment and comment
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.issue.number;
          const environmentName = `preview-pr-${prNumber}`;
          
          try {
            // Delete the environment
            await github.rest.repos.deleteAnEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: environmentName
            });
            
            console.log(`Environment ${environmentName} deleted successfully`);
            
            // Add cleanup comment to PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🧹 **Deploy Preview Cleaned Up**
              
The preview environment for this PR has been automatically deleted.

---
*Cleanup completed for PR #${prNumber}*`
            });
            
          } catch (error) {
            console.log(`Environment ${environmentName} not found or already deleted: ${error.message}`);
          } 