name: Deploy PR previews  # Name of your workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, closed] # Trigger on PR open, reopen, sync, or close

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  deployments: write
  
jobs:
  deploy-preview:
    runs-on: ubuntu-latest  # Use a suitable runner environment

    steps:
      - uses: actions/checkout@v4  # Checkout the code from the pull request

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Antora
        run: npm install antora

      - name: Generate Site
        run: npx antora antora-playbook.yml

      - name: Disable Jekyll
        run: touch build/site/.nojekyll

      - name: Deploy preview  # Deploy the built site as a preview
        uses: rossjrw/pr-preview-action@v1  # Use the pr-preview-action
        with:
          source-dir: ./build/site  # Directory containing the built site files
          preview-branch: gh-pages  # The branch to deploy previews to (usually gh-pages for GitHub Pages)
          umbrella-dir: pr-preview  # Directory within the preview branch to store previews
          action: auto  # Automatically handles deployment and cleanup (deploy/remove)

      - name: Remove preview on closed PR  # Remove the preview when the PR is closed
        if: github.event.action == 'closed' #  Condition to run only on PR close
        uses: rossjrw/pr-preview-action@v1  # Use the pr-preview-action again
        with:
          action: remove  #  Specify the action to remove the preview
          umbrella-dir: pr-preview  #  Directory where previews are stored
