name: Publish to GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: github-pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Antora
      run: npm install antora

    - name: Generate Site
      run: npx antora antora-playbook.yml

    - name: Post-process paths for VC context/schema docs
      run: |
        mkdir build/site/identity/1.1
        mv build/site/identity/1.1-draft/_attachments/ica build/site/identity/1.1/ica
        # IMPORTANT: This will have be updated when 1.1-draft becomes 1.1 final.

    - name: Disable Jekyll
      run: touch .nojekyll

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build/site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
